import MatchDial from "./MatchDial";

export default function ProductCard({ product }) {
  return (
    <div className="group border border-ink-700 bg-ink-800/60 rounded-sm p-5 flex flex-col gap-3 hover:border-gold-600/60 transition-colors">
      <div className="flex items-start justify-between gap-3">
        <div>
          <p className="font-mono text-[10px] tracking-widest text-mute uppercase mb-1">
            {product.category}
          </p>
          <h3 className="font-display text-lg text-parchment leading-snug">
            {product.name}
          </h3>
        </div>
        <MatchDial score={product.match_score} />
      </div>

      <p className="text-sm text-mute leading-relaxed">{product.description}</p>

      <div className="flex items-center justify-between pt-2 border-t border-ink-700">
        <span className="font-mono text-gold-400 text-base">
          ₹{product.price.toLocaleString("en-IN")}
        </span>
        <span className="font-mono text-xs text-mute">{product.rating}★</span>
      </div>

      <div className="flex items-start justify-between gap-2">
        <p className="text-xs text-sage/90 italic leading-relaxed flex-1">{product.reason}</p>
        {product.reason_source === "llm" && (
          <span
            title="Explanation generated by an LLM"
            className="font-mono text-[9px] tracking-wider text-gold-500/80 border border-gold-600/40 rounded-full px-1.5 py-0.5 shrink-0"
          >
            AI
          </span>
        )}
      </div>
    </div>
  );
}
